on: [push, pull_request]
jobs:
  demo-ci-runner:
    runs-on: ubuntu-latest

    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306 
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:

      - name: Checkout app code
        uses: actions/checkout@v2

      - uses: shivammathur/setup-php@verbose
        with:
          php-version: 7.4
          coverage: xdebug
        env:
          update: true

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create test database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'

      - name: Setup Database
        run: |
          php artisan migrate --no-interaction -vvv
          php artisan db:seed

      - name: Run Testsuite with Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)