on: [push, pull_request]
jobs:
  demo-ci-runner:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Install sudo package and curl
      run: | 
        apt update 
        apt install sudo 
        apt install -y curl

    - name: Checkout app code
      uses: actions/checkout@v2

    - name: Xdebug Action
      uses: MilesChou/docker-xdebug@master
      
    - uses: php-actions/composer@v5
      with:
        command: dump-autoload
        only_args: --no-dev --no-interaction --classmap-authoritative

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Setup Database
      run: |
        php artisan migrate --no-interaction -vvv
        php artisan db:seed

    - name: Run Testsuite with Coverage
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage report
      run: "bash <(curl -s https://qa.codecov.dev/bash )"