on: push
name: CI
jobs:
  demo-ci-runner:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Setup Database
      run: |
        php artisan migrate --no-interaction -vvv
        php artisan db:seed

    - name: Run Testsuite with Coverage
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage report
      run: "bash <(curl -s https://qa.codecov.dev/bash)"